// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU3s77ODRwAirWKi_X3R7F6GyX_Nf6zNc',
    appId: '1:853568610093:web:7cf0fa7e01a74cb50cbda4',
    messagingSenderId: '853568610093',
    projectId: 'wowstatsds',
    authDomain: 'wowstatsds.firebaseapp.com',
    storageBucket: 'wowstatsds.appspot.com',
    measurementId: 'G-FEK28HMSJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWQAjtXC0KzZuf0vaHH0Lmsf2MXSrf3qs',
    appId: '1:853568610093:android:621d9944e1d645290cbda4',
    messagingSenderId: '853568610093',
    projectId: 'wowstatsds',
    storageBucket: 'wowstatsds.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC2fc-RPXEWizwIycBWJxm6ShB6s4Iv40',
    appId: '1:853568610093:ios:903436bc054afd900cbda4',
    messagingSenderId: '853568610093',
    projectId: 'wowstatsds',
    storageBucket: 'wowstatsds.appspot.com',
    iosBundleId: 'com.example.wowStatsDs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC2fc-RPXEWizwIycBWJxm6ShB6s4Iv40',
    appId: '1:853568610093:ios:903436bc054afd900cbda4',
    messagingSenderId: '853568610093',
    projectId: 'wowstatsds',
    storageBucket: 'wowstatsds.appspot.com',
    iosBundleId: 'com.example.wowStatsDs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU3s77ODRwAirWKi_X3R7F6GyX_Nf6zNc',
    appId: '1:853568610093:web:672bbbb7b900c0400cbda4',
    messagingSenderId: '853568610093',
    projectId: 'wowstatsds',
    authDomain: 'wowstatsds.firebaseapp.com',
    storageBucket: 'wowstatsds.appspot.com',
    measurementId: 'G-D46DKQ8HGN',
  );

  
}
